# Generated by Django 4.2.6 on 2023-11-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmotionVector",
            fields=[
                (
                    "emotion",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("vector", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TrackVibe",
            fields=[
                (
                    "track_id",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("track_lyrics_vibe", models.CharField(max_length=250, null=True)),
                ("track_audio_vibe", models.CharField(max_length=250, null=True)),
                ("upvote_count", models.IntegerField(default=0)),
                ("downvote_count", models.IntegerField(default=0)),
            ],
        ),
    ]
