# Generated by Django 4.2.6 on 2023-11-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "track_id",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("track_name", models.CharField(max_length=250)),
                ("track_cover_url", models.TextField(null=True)),
                ("artist_name", models.CharField(max_length=250)),
                ("artist_id", models.CharField(max_length=255)),
                ("album_name", models.CharField(max_length=250)),
                ("album_id", models.CharField(max_length=250)),
                ("track_lyrics_vibe", models.CharField(max_length=250, null=True)),
                ("track_audio_vibe", models.CharField(max_length=250, null=True)),
                ("upvote_count", models.IntegerField(default=0)),
                ("downvote_count", models.IntegerField(default=0)),
                ("track_spotify_popularity", models.IntegerField(default=0)),
                (
                    "track_acousticness",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "track_danceability",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "track_energy",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "track_loudness",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "track_instrumentalness",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "track_speechiness",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "track_valence",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
            ],
        ),
    ]
