# Generated by Django 4.2.6 on 2023-12-08 03:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("followers", models.IntegerField(default=0)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                ("image", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("popularity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("name", models.TextField(null=True)),
                ("popularity", models.IntegerField(default=0)),
                ("album_name", models.TextField(null=True)),
                ("album_release_date", models.TextField(null=True)),
                ("album_images_large", models.TextField(null=True)),
                ("album_images_small", models.TextField(null=True)),
                (
                    "artist_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                (
                    "artist_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                ("acousticness", models.FloatField(default=0.0)),
                ("danceability", models.FloatField(default=0.0)),
                ("energy", models.FloatField(default=0.0)),
                ("instrumentalness", models.FloatField(default=0.0)),
                ("loudness", models.FloatField(default=0.0)),
                ("speechiness", models.FloatField(default=0.0)),
                ("valence", models.FloatField(default=0.0)),
            ],
        ),
    ]
