# Generated by Django 4.2.6 on 2023-10-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=250)),
                ("username", models.CharField(max_length=125)),
                ("total_followers", models.IntegerField()),
                ("profile_image_url", models.URLField(null=True)),
                ("user_country", models.CharField(max_length=200, null=True)),
                ("user_last_login", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Vibe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=250)),
                ("user_vibe", models.CharField(max_length=100)),
                ("vibe_time", models.DateTimeField()),
            ],
        ),
    ]
