# Generated by Django 4.2.6 on 2023-11-04 02:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=125)),
                ("total_followers", models.IntegerField()),
                ("profile_image_url", models.TextField(null=True)),
                ("user_country", models.CharField(max_length=200, null=True)),
                ("user_last_login", models.DateTimeField()),
                ("user_bio", models.TextField(null=True)),
                ("user_city", models.CharField(max_length=255, null=True)),
                ("user_total_friends", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vibe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=250)),
                ("user_lyrics_vibe", models.CharField(max_length=250, null=True)),
                ("user_audio_vibe", models.CharField(max_length=250, null=True)),
                (
                    "user_acousticness",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "user_danceability",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "user_energy",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "user_valence",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "recent_track",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                (
                    "recommended_tracks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                (
                    "top_track",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                (
                    "top_artist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                (
                    "top_genre",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                ("vibe_time", models.DateTimeField()),
            ],
        ),
    ]
