# Generated by Django 4.2.6 on 2023-11-07 04:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=250)),
                ("time", models.DateTimeField()),
                (
                    "recommended_tracks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                (
                    "top_track",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                (
                    "top_artist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
                (
                    "top_genre",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), null=True, size=20
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="vibe",
            name="recommended_tracks",
        ),
        migrations.RemoveField(
            model_name="vibe",
            name="top_artist",
        ),
        migrations.RemoveField(
            model_name="vibe",
            name="top_genre",
        ),
        migrations.RemoveField(
            model_name="vibe",
            name="top_track",
        ),
    ]
